### ISSUE TITLE
Creating tasks in GitHub issues

### ISSUE THREAD

**Issue by GordonBeeming** [GordonBeeming-Content/GitHubTip-UseTasklists#2]
In order to complete this work, we need to complete the following tasks

```[tasklist]
## Tasks
- [x] Task 4 343
- [x] Task 1
- [ ] #4
- [ ] Task 2
```

## Acceptance Criteria

- [ ] We need to easily see the tasks in the GitHub issue
- [ ] We should easily know when all tasks are complete
- [ ] We should need to go to markdown to add new tasks
